language: swift
osx_image: xcode12.2
before_install:
  - yes | gem update --system --force
  - gem install bundler -v "~>2.2"
  - brew install libsodium
install: 
  - bundle install
script: 
  - fastlane build_and_test
